# Generated by Django 5.0.7 on 2024-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_brand_branda_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='ratting',
            field=models.FloatField(default=0.0),
        ),
    ]
